"""The Atlas — the human-facing half of a Brain.

The onboarding document that is always true because it is generated, not
maintained. A new engineer should be able to read it and know what this
repository is, how to run it, where the risk sits, and who to ask.

Two rules shape it. Every claim carries how it was established, so a reader can
tell "the tests run with make test, we watched it happen" from "probably make
test, nobody has checked". And it ends by stating what the Brain does not know —
a document that hides its gaps teaches people to trust it where it is weakest.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from .envelope import Method, Status
from .model import LAYER_NAMES, REPO, Brain, Edge, Layer, Node

BAR_WIDTH = 18


def human_bytes(n: int) -> str:
    step = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if step < 1024 or unit == "GB":
            return f"{step:,.0f} {unit}" if unit == "B" else f"{step:,.1f} {unit}"
        step /= 1024
    return f"{n} B"


def provenance(env) -> str:
    """A short, honest tag a reader can act on."""
    if env.status is Status.REFUTED:
        return "`REFUTED`"
    if env.method is Method.OBSERVED:
        return f"`OBSERVED` verified at `{(env.verified_at or '')[:7]}`"
    if env.method is Method.DERIVED:
        return f"`DERIVED` {env.confidence:.2f} — inferred, not verified"
    if env.method is Method.INFERRED:
        return f"`INFERRED` {env.confidence:.2f} — model-generated"
    if env.method is Method.ASSERTED:
        return "`ASSERTED` by a human"
    return "`EXTRACTED`"


def _bar(value: float, peak: float, width: int = BAR_WIDTH) -> str:
    if peak <= 0:
        return ""
    return "█" * max(1, round(width * value / peak))


class Atlas:
    def __init__(self, brain: Brain) -> None:
        self.brain = brain
        self.out: list[str] = []

    # -- helpers -----------------------------------------------------------

    def fact(self, predicate: str, subject: str = REPO):
        return self.brain.fact(subject, predicate)

    def value(self, predicate: str, default: Any = None) -> Any:
        found = self.fact(predicate)
        return found.value if found is not None else default

    def w(self, line: str = "") -> None:
        self.out.append(line)

    def h(self, level: int, text: str) -> None:
        self.w()
        self.w(f"{'#' * level} {text}")
        self.w()

    # -- render ------------------------------------------------------------

    def render(self) -> str:
        self.out = []
        self._header()
        self._what()
        self._how()
        self._shape()
        self._risk()
        self._people()
        self._pipelines()
        self._gaps()
        self._footer()
        return "\n".join(self.out).rstrip() + "\n"

    def _header(self) -> None:
        m = self.brain.manifest
        name = self.value("repo_name") or m.repo or "this repository"
        self.w(f"# {name}")
        self.w()
        self.w("> Generated by CodeBrain. Do not edit — regenerate with `codebrain build`.")
        self.w(">")
        self.w(f"> Commit `{(m.as_of or '?')[:8]}`"
               + (f" on `{m.branch}`" if m.branch else "")
               + f" · built {m.built_at or '?'} · {len(self.brain)} records")

    def _what(self) -> None:
        mix = self.value("language_mix") or {}
        files = self.value("file_count")
        size = self.value("total_bytes")
        primary = self.value("primary_language")
        if files is None and not mix:
            return

        self.h(2, "What this is")
        bits = []
        if primary:
            bits.append(f"A **{primary}** repository")
        if files is not None:
            bits.append(f"{files:,} files")
        if size is not None:
            bits.append(human_bytes(size))
        if bits:
            self.w(" · ".join(bits) + ".")
            self.w()

        source = {k: v for k, v in mix.items() if k != "unknown"}
        if source:
            peak = max(source.values())
            self.w("| Language | Files | |")
            self.w("|---|---:|---|")
            for language, count in list(source.items())[:10]:
                self.w(f"| {language} | {count} | {_bar(count, peak)} |")

    def _how(self) -> None:
        intents = [("test", "Test"), ("build", "Build"), ("run", "Run"), ("lint", "Lint")]
        rows = [(label, self.fact(f"{key}_command")) for key, label in intents]
        rows = [(label, f) for label, f in rows if f is not None]
        if not rows:
            return

        self.h(2, "How to work with it")
        self.w("| | Command | Source | Confidence |")
        self.w("|---|---|---|---|")
        for label, found in rows:
            src = found.attrs.get("source", "—")
            self.w(f"| **{label}** | `{found.value}` | {src} | {provenance(found.env)} |")

        unverified = [f for _, f in rows if f.env.method is not Method.OBSERVED]
        if unverified:
            self.w()
            self.w(f"> {len(unverified)} of these command(s) have never been executed by "
                   "CodeBrain. They are the best candidate from the evidence, not a "
                   "confirmed fact — treat them as a starting point until `codebrain "
                   "verify` promotes them.")

        alternatives = [(label, f) for label, f in rows if f.attrs.get("alternatives")]
        if alternatives:
            self.w()
            self.w("<details><summary>Other candidates that were considered</summary>")
            self.w()
            for label, found in alternatives:
                for alt in found.attrs["alternatives"]:
                    self.w(f"- **{label}** — `{alt['command']}` ({alt['source']})")
            self.w()
            self.w("</details>")

    def _shape(self) -> None:
        modules = [n for n in self.brain.nodes.values()
                   if isinstance(n, Node) and n.kind == "module"]
        if not modules:
            return

        defines: dict[str, int] = defaultdict(int)
        imported_by: dict[str, int] = defaultdict(int)
        for edge in self.brain.edges.values():
            if edge.kind == "defines":
                defines[edge.src] += 1
            elif edge.kind == "imports":
                imported_by[edge.dst] += 1

        self.h(2, "Shape")
        py = self.value("python_summary") or {}
        ts = self.value("typescript_summary") or {}
        summary = []
        if py:
            summary.append(f"**Python** — {py.get('modules', 0)} modules, "
                           f"{py.get('symbols', 0)} symbols, "
                           f"{py.get('call_edges', 0)} resolved calls")
        if ts:
            summary.append(f"**TypeScript/JS** — {ts.get('modules', 0)} modules, "
                           f"{ts.get('symbols', 0)} declarations")
        for line in summary:
            self.w(f"- {line}")
        if summary:
            self.w()

        # Most depended-upon modules: what an agent breaks if it gets them wrong.
        ranked = sorted(modules, key=lambda n: (-imported_by[n.id], -defines[n.id], n.key)
                        )[:12]
        if any(imported_by[n.id] or defines[n.id] for n in ranked):
            self.w("| Module | Symbols | Imported by |")
            self.w("|---|---:|---:|")
            for node in ranked:
                self.w(f"| `{node.key}` | {defines[node.id]} | {imported_by[node.id]} |")

    def _risk(self) -> None:
        hotspots = self.value("hotspots") or []
        bus_factor = self._bus_factor()
        coupling = self._coupling()
        if not (hotspots or bus_factor or coupling):
            return

        self.h(2, "Where the risk is")

        if hotspots:
            self.w("**Hotspots** — changed most, and most heavily. Churn is the best "
                   "cheap predictor of where the next defect lands.")
            self.w()
            peak = max(h["score"] for h in hotspots)
            self.w("| File | Commits | Lines changed | |")
            self.w("|---|---:|---:|---|")
            for spot in hotspots[:10]:
                self.w(f"| `{spot['path']}` | {spot['commits']} | "
                       f"{spot['lines_changed']:,} | {_bar(spot['score'], peak)} |")
            self.w()

        if bus_factor:
            self.w(f"**Single-author files** — {len(bus_factor)} file(s) have only ever "
                   "been touched by one person. If that person is gone, so is the "
                   "understanding.")
            self.w()
            for path, author in bus_factor[:10]:
                self.w(f"- `{path}` — {author}")
            self.w()

        if coupling:
            self.w("**Coupled files** — these change together. Editing one without the "
                   "other has historically been a mistake.")
            self.w()
            for src, dst, strength, commits in coupling[:10]:
                self.w(f"- `{src}` ↔ `{dst}` — {commits} shared commits "
                       f"({strength:.0%} of their changes)")

    def _bus_factor(self) -> list[tuple[str, str]]:
        risky: list[tuple[str, str]] = []
        for found in self.brain.facts.values():
            if found.predicate != "ownership":
                continue
            value = found.value or {}
            if value.get("distinct_authors") == 1:
                path = found.subject.split(":file:", 1)[-1]
                risky.append((path, value.get("primary_author", "?")))
        risky.sort()
        return risky

    def _coupling(self) -> list[tuple[str, str, float, int]]:
        pairs = []
        for edge in self.brain.edges.values():
            if not isinstance(edge, Edge) or edge.kind != "changed_with":
                continue
            pairs.append((
                edge.src.split(":file:", 1)[-1],
                edge.dst.split(":file:", 1)[-1],
                float(edge.attrs.get("strength", 0)),
                int(edge.attrs.get("commits", 0)),
            ))
        pairs.sort(key=lambda p: (-p[2], -p[3], p[0]))
        return pairs

    def _people(self) -> None:
        authors = self.value("top_authors") or []
        if not authors:
            return
        self.h(2, "Who knows it")
        total = sum(a["commits"] for a in authors) or 1
        self.w("| Author | Commits | Share |")
        self.w("|---|---:|---:|")
        for author in authors[:10]:
            self.w(f"| {author['author']} | {author['commits']} | "
                   f"{author['commits'] / total:.0%} |")

    def _pipelines(self) -> None:
        pipelines = [n for n in self.brain.nodes.values()
                     if isinstance(n, Node) and n.kind == "pipeline"]
        containers = [n for n in self.brain.nodes.values()
                      if isinstance(n, Node) and n.kind == "container"]
        owners = self.value("codeowners") or []
        if not (pipelines or containers or owners):
            return

        self.h(2, "Shipping")
        for node in sorted(pipelines, key=lambda n: n.key):
            steps = node.attrs.get("step_count", 0)
            self.w(f"- **Pipeline** `{node.key}` — {steps} run step(s) "
                   f"{provenance(node.env)}")
        for node in sorted(containers, key=lambda n: n.key):
            base = node.attrs.get("base_image") or "?"
            self.w(f"- **Container** `{node.key}` — from `{base}`")
        if owners:
            self.w(f"- **CODEOWNERS** — {len(owners)} rule(s); these paths need a "
                   "named reviewer")

    def _gaps(self) -> None:
        gaps: list[str] = []

        unparsed = self.value("python_unparsed_files") or []
        if unparsed:
            gaps.append(f"{len(unparsed)} Python file(s) could not be parsed and are "
                        "absent from the structure layer.")

        ts_gap = self.value("typescript_coverage_gap")
        if ts_gap:
            gaps.append(f"TypeScript/JavaScript has no call graph — {ts_gap.get('impact')}.")

        history_gap = self.value("history_coverage_gap")
        if history_gap:
            gaps.append(f"{history_gap.get('files_without_history')} file(s) have no "
                        f"history signal ({history_gap.get('reason')}).")

        empty = [LAYER_NAMES[layer] for layer in Layer
                 if not self.brain.by_layer(layer) and layer is not Layer.L7]
        if empty:
            gaps.append("Layers not yet populated: " + ", ".join(empty) + ".")

        unverified = sum(1 for r in self.brain.records()
                         if r.env.method in (Method.DERIVED, Method.INFERRED))
        if unverified:
            gaps.append(f"{unverified} claim(s) are inferred rather than extracted and "
                        "have not been verified by execution.")

        if not gaps:
            return

        self.h(2, "What this Brain does not know")
        self.w("Stated plainly, because a document that hides its gaps gets trusted "
               "exactly where it is weakest.")
        self.w()
        for gap in gaps:
            self.w(f"- {gap}")

    def _footer(self) -> None:
        self.w()
        self.w("---")
        self.w()
        self.w(f"CodeBrain {self.brain.manifest.codebrain_version} · "
               f"schema {self.brain.manifest.schema_version} · "
               f"providers: {', '.join(self.brain.manifest.providers) or 'none'}")


def render(brain: Brain) -> str:
    return Atlas(brain).render()
